language: rust
os:
  - macos
rust:
  - stable
  - beta
  - nightly
script:
  - cd lib/bootstrap_rs
  - cargo build
  - cargo build --example window
matrix:
  allow_failures:
    - rust:
      - stable
      - beta
