[package]

name = "rusty_window"
version = "0.0.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[[bin]]
name = "rusty_window"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.bootstrap-rs]
version = "*"
path = "lib"
