[package]

name = "gunship"
version = "0.0.1"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[lib]
name = "gunship"

[features]
default = ["timing"]

timing = []
hotloading = []

[dependencies.fnv]
version = "*"
path = "lib/fnv"

[dependencies.bootstrap_rs]
version = "*"
path = "lib/bootstrap_rs"

[dependencies.bootstrap_audio]
version = "*"
path = "lib/bootstrap_audio"

[dependencies.parse_collada]
version = "*"
path = "lib/parse_collada"

[dependencies.polygon]
version = "*"
path = "lib/polygon_rs"

[dependencies.polygon_math]
version = "*"
path = "lib/polygon_math"

[dependencies.stopwatch] # TODO: Make this a dev dependency somehow?
version = "*"
path = "lib/stopwatch"

[profile.release]
debug = true

[[example]]
name = "create_destroy"
path = "examples/benchmarks/create_destroy.rs"

[dev_dependencies.rand]
version = "*"

[[example]]
name = "circle_movement"
path = "examples/benchmarks/circle_movement.rs"

[[example]]
name = "circle_collision"
path = "examples/benchmarks/circle_collision.rs"
