[package]

name = "render_rs"
version = "0.0.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[[bin]]
name = "render_rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.bootstrap-rs]
version = "*"
path = "lib/bootstrap-rs"

[dependencies.render_math]
version = "*"
path = "lib/render_math"

[dependencies.parse_collada]
version = "*"
path = "lib/parse_collada"
