[package]

name = "polygon-rs"
version = "0.0.1"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[[bin]]
name = "polygon_rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.bootstrap-rs]
version = "*"
path = "lib/bootstrap-rs"

[dependencies.polygon-math]
version = "*"
path = "lib/polygon-math"

[dependencies.parse-collada]
version = "*"
path = "lib/parse-collada"
