[package]

name = "gunship"
version = "0.0.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[dependencies.bootstrap_rs]
version = "*"
path = "lib/bootstrap_rs"

[dependencies.parse_collada]
version = "*"
path = "lib/parse_collada"

[dependencies.polygon_rs]
version = "*"
path = "lib/polygon_rs"

[dependencies.polygon_math]
version = "*"
path = "lib/polygon_math"
